default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: sample_app_development
  username: nguyenit2k2
  password: hoangnguyen123
  host: localhost

test:
  <<: *default
  database: sample_app_test
  username: nguyenit2k2
  password: hoangnguyen123
  host: localhost

production:
  <<: *default
  database: sample_app_production
  username: nguyenit2k2
  password: hoangnguyen123
  host: localhost
  # Thay thế bằng URL của cơ sở dữ liệu PostgreSQL trong môi trường sản xuất
  # Các thông tin bảo mật nên được lưu trữ dưới dạng biến môi trường
